name: Release
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Workflow Title"
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Daily Status
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            SSH_PORT : ${{ secrets.PORT  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} -p ${SSH_PORT}'

            pwd
          '
