name: Release
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Workflow Title"
        required: true
steps:
      - uses: actions/checkout@v3
      - name: testing workflow
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            PORT : ${{ secrets.PORT  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} -p ${PORT} '

            pwd
          '
